# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.CBB1 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB1.setFont(font)
        self.CBB1.setStyleSheet("color: blue")
        self.CBB1.setObjectName("CBB1")
        self.gridLayout.addWidget(self.CBB1, 5, 0, 1, 1)
        self.CBG29 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG29.setFont(font)
        self.CBG29.setStyleSheet("color: green")
        self.CBG29.setObjectName("CBG29")
        self.gridLayout.addWidget(self.CBG29, 4, 7, 1, 1)
        self.CBG28 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG28.setFont(font)
        self.CBG28.setStyleSheet("color: green")
        self.CBG28.setObjectName("CBG28")
        self.gridLayout.addWidget(self.CBG28, 7, 6, 1, 1)
        self.CBG1 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG1.setFont(font)
        self.CBG1.setStyleSheet("color: green")
        self.CBG1.setObjectName("CBG1")
        self.gridLayout.addWidget(self.CBG1, 2, 0, 1, 1)
        self.CBG7 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG7.setFont(font)
        self.CBG7.setStyleSheet("color: green")
        self.CBG7.setObjectName("CBG7")
        self.gridLayout.addWidget(self.CBG7, 6, 1, 1, 1)
        self.CBG31 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG31.setFont(font)
        self.CBG31.setStyleSheet("color: green")
        self.CBG31.setObjectName("CBG31")
        self.gridLayout.addWidget(self.CBG31, 6, 7, 1, 1)
        self.CBG21 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG21.setFont(font)
        self.CBG21.setStyleSheet("color: green")
        self.CBG21.setObjectName("CBG21")
        self.gridLayout.addWidget(self.CBG21, 2, 5, 1, 1)
        self.CBG27 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG27.setFont(font)
        self.CBG27.setStyleSheet("color: green")
        self.CBG27.setObjectName("CBG27")
        self.gridLayout.addWidget(self.CBG27, 6, 6, 1, 1)
        self.CBG10 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG10.setFont(font)
        self.CBG10.setStyleSheet("color: green")
        self.CBG10.setObjectName("CBG10")
        self.gridLayout.addWidget(self.CBG10, 4, 2, 1, 1)
        self.CBB2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB2.setFont(font)
        self.CBB2.setStyleSheet("color: blue")
        self.CBB2.setObjectName("CBB2")
        self.gridLayout.addWidget(self.CBB2, 2, 1, 1, 1)
        self.CBG12 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG12.setFont(font)
        self.CBG12.setStyleSheet("color: green")
        self.CBG12.setObjectName("CBG12")
        self.gridLayout.addWidget(self.CBG12, 7, 2, 1, 1)
        self.CBB3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB3.setFont(font)
        self.CBB3.setStyleSheet("color: blue")
        self.CBB3.setObjectName("CBB3")
        self.gridLayout.addWidget(self.CBB3, 6, 2, 1, 1)
        self.CBG2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG2.setFont(font)
        self.CBG2.setStyleSheet("color: green")
        self.CBG2.setObjectName("CBG2")
        self.gridLayout.addWidget(self.CBG2, 4, 0, 1, 1)
        self.CBG5 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG5.setFont(font)
        self.CBG5.setStyleSheet("color: green")
        self.CBG5.setObjectName("CBG5")
        self.gridLayout.addWidget(self.CBG5, 4, 1, 1, 1)
        self.CBB9 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB9.setFont(font)
        self.CBB9.setStyleSheet("color: blue")
        self.CBB9.setObjectName("CBB9")
        self.gridLayout.addWidget(self.CBB9, 6, 8, 1, 1)
        self.CBG6 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG6.setFont(font)
        self.CBG6.setStyleSheet("color: green")
        self.CBG6.setObjectName("CBG6")
        self.gridLayout.addWidget(self.CBG6, 5, 1, 1, 1)
        self.CBG18 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG18.setFont(font)
        self.CBG18.setStyleSheet("color: green")
        self.CBG18.setObjectName("CBG18")
        self.gridLayout.addWidget(self.CBG18, 4, 4, 1, 1)
        self.CBG33 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG33.setFont(font)
        self.CBG33.setStyleSheet("color: green")
        self.CBG33.setObjectName("CBG33")
        self.gridLayout.addWidget(self.CBG33, 2, 8, 1, 1)
        self.CBG9 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG9.setFont(font)
        self.CBG9.setStyleSheet("color: green")
        self.CBG9.setObjectName("CBG9")
        self.gridLayout.addWidget(self.CBG9, 2, 2, 1, 1)
        self.CBB6 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB6.setFont(font)
        self.CBB6.setStyleSheet("color: blue")
        self.CBB6.setObjectName("CBB6")
        self.gridLayout.addWidget(self.CBB6, 7, 5, 1, 1)
        self.CBG8 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG8.setFont(font)
        self.CBG8.setStyleSheet("color: green")
        self.CBG8.setObjectName("CBG8")
        self.gridLayout.addWidget(self.CBG8, 7, 1, 1, 1)
        self.CBG22 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG22.setFont(font)
        self.CBG22.setStyleSheet("color: green")
        self.CBG22.setObjectName("CBG22")
        self.gridLayout.addWidget(self.CBG22, 4, 5, 1, 1)
        self.CBG30 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG30.setFont(font)
        self.CBG30.setStyleSheet("color: green")
        self.CBG30.setObjectName("CBG30")
        self.gridLayout.addWidget(self.CBG30, 5, 7, 1, 1)
        self.CBG24 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG24.setFont(font)
        self.CBG24.setStyleSheet("color: green")
        self.CBG24.setObjectName("CBG24")
        self.gridLayout.addWidget(self.CBG24, 6, 5, 1, 1)
        self.BtnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCreate.setObjectName("BtnCreate")
        self.gridLayout.addWidget(self.BtnCreate, 9, 6, 1, 3)
        self.LblLeds = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblLeds.setFont(font)
        self.LblLeds.setObjectName("LblLeds")
        self.gridLayout.addWidget(self.LblLeds, 0, 0, 1, 4)
        self.CBG34 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG34.setFont(font)
        self.CBG34.setStyleSheet("color: green")
        self.CBG34.setObjectName("CBG34")
        self.gridLayout.addWidget(self.CBG34, 4, 8, 1, 1)
        self.CBG11 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG11.setFont(font)
        self.CBG11.setStyleSheet("color: green")
        self.CBG11.setObjectName("CBG11")
        self.gridLayout.addWidget(self.CBG11, 5, 2, 1, 1)
        self.CBG3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG3.setFont(font)
        self.CBG3.setStyleSheet("color: green")
        self.CBG3.setObjectName("CBG3")
        self.gridLayout.addWidget(self.CBG3, 6, 0, 1, 1)
        self.CBG19 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG19.setFont(font)
        self.CBG19.setStyleSheet("color: green")
        self.CBG19.setObjectName("CBG19")
        self.gridLayout.addWidget(self.CBG19, 6, 4, 1, 1)
        self.CBG26 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG26.setFont(font)
        self.CBG26.setStyleSheet("color: green")
        self.CBG26.setObjectName("CBG26")
        self.gridLayout.addWidget(self.CBG26, 5, 6, 1, 1)
        self.CBG36 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG36.setFont(font)
        self.CBG36.setStyleSheet("color: green")
        self.CBG36.setObjectName("CBG36")
        self.gridLayout.addWidget(self.CBG36, 7, 8, 1, 1)
        self.CBG32 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG32.setFont(font)
        self.CBG32.setStyleSheet("color: green")
        self.CBG32.setObjectName("CBG32")
        self.gridLayout.addWidget(self.CBG32, 7, 7, 1, 1)
        self.CBG14 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG14.setFont(font)
        self.CBG14.setStyleSheet("color: green")
        self.CBG14.setObjectName("CBG14")
        self.gridLayout.addWidget(self.CBG14, 5, 3, 1, 1)
        self.CBG23 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG23.setFont(font)
        self.CBG23.setStyleSheet("color: green")
        self.CBG23.setObjectName("CBG23")
        self.gridLayout.addWidget(self.CBG23, 5, 5, 1, 1)
        self.CBG4 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG4.setFont(font)
        self.CBG4.setStyleSheet("color: green")
        self.CBG4.setObjectName("CBG4")
        self.gridLayout.addWidget(self.CBG4, 7, 0, 1, 1)
        self.CBG25 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG25.setFont(font)
        self.CBG25.setStyleSheet("color: green")
        self.CBG25.setObjectName("CBG25")
        self.gridLayout.addWidget(self.CBG25, 2, 6, 1, 1)
        self.CBG20 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG20.setFont(font)
        self.CBG20.setStyleSheet("color: green")
        self.CBG20.setObjectName("CBG20")
        self.gridLayout.addWidget(self.CBG20, 7, 4, 1, 1)
        self.CBG17 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG17.setFont(font)
        self.CBG17.setStyleSheet("color: green")
        self.CBG17.setObjectName("CBG17")
        self.gridLayout.addWidget(self.CBG17, 2, 4, 1, 1)
        self.CBG16 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG16.setFont(font)
        self.CBG16.setStyleSheet("color: green")
        self.CBG16.setObjectName("CBG16")
        self.gridLayout.addWidget(self.CBG16, 7, 3, 1, 1)
        self.CBB8 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB8.setFont(font)
        self.CBB8.setStyleSheet("color: blue")
        self.CBB8.setObjectName("CBB8")
        self.gridLayout.addWidget(self.CBB8, 2, 7, 1, 1)
        self.CBB5 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB5.setFont(font)
        self.CBB5.setStyleSheet("color: blue")
        self.CBB5.setObjectName("CBB5")
        self.gridLayout.addWidget(self.CBB5, 5, 4, 1, 1)
        self.CBG35 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG35.setFont(font)
        self.CBG35.setStyleSheet("color: green")
        self.CBG35.setObjectName("CBG35")
        self.gridLayout.addWidget(self.CBG35, 5, 8, 1, 1)
        self.CBG15 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG15.setFont(font)
        self.CBG15.setStyleSheet("color: green")
        self.CBG15.setObjectName("CBG15")
        self.gridLayout.addWidget(self.CBG15, 6, 3, 1, 1)
        self.CBB4 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB4.setFont(font)
        self.CBB4.setStyleSheet("color: blue")
        self.CBB4.setObjectName("CBB4")
        self.gridLayout.addWidget(self.CBB4, 4, 3, 1, 1)
        self.CBAll = QtWidgets.QCheckBox(self.centralwidget)
        self.CBAll.setTristate(True)
        self.CBAll.setObjectName("CBAll")
        self.gridLayout.addWidget(self.CBAll, 1, 0, 1, 1)
        self.CBB7 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBB7.setFont(font)
        self.CBB7.setStyleSheet("color: blue")
        self.CBB7.setObjectName("CBB7")
        self.gridLayout.addWidget(self.CBB7, 4, 6, 1, 1)
        self.CBG13 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CBG13.setFont(font)
        self.CBG13.setStyleSheet("color: green")
        self.CBG13.setObjectName("CBG13")
        self.gridLayout.addWidget(self.CBG13, 2, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("c")
        self.tabWidget.setObjectName("tabWidget")
        self.TabTO = QtWidgets.QWidget()
        self.TabTO.setObjectName("TabTO")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TabTO)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LblTOStartFrom = QtWidgets.QLabel(self.TabTO)
        self.LblTOStartFrom.setObjectName("LblTOStartFrom")
        self.gridLayout_2.addWidget(self.LblTOStartFrom, 0, 1, 1, 1)
        self.CBTOStart = QtWidgets.QCheckBox(self.TabTO)
        self.CBTOStart.setChecked(True)
        self.CBTOStart.setObjectName("CBTOStart")
        self.gridLayout_2.addWidget(self.CBTOStart, 0, 0, 1, 1)
        self.CBTOPeriod = QtWidgets.QCheckBox(self.TabTO)
        self.CBTOPeriod.setObjectName("CBTOPeriod")
        self.gridLayout_2.addWidget(self.CBTOPeriod, 2, 0, 1, 1)
        self.LblTOBrFrom = QtWidgets.QLabel(self.TabTO)
        self.LblTOBrFrom.setObjectName("LblTOBrFrom")
        self.gridLayout_2.addWidget(self.LblTOBrFrom, 1, 1, 1, 1)
        self.SpinTOBrFrom = QtWidgets.QSpinBox(self.TabTO)
        self.SpinTOBrFrom.setEnabled(False)
        self.SpinTOBrFrom.setMaximum(255)
        self.SpinTOBrFrom.setObjectName("SpinTOBrFrom")
        self.gridLayout_2.addWidget(self.SpinTOBrFrom, 1, 2, 1, 1)
        self.SpinTOStartFrom = QtWidgets.QSpinBox(self.TabTO)
        self.SpinTOStartFrom.setEnabled(False)
        self.SpinTOStartFrom.setObjectName("SpinTOStartFrom")
        self.gridLayout_2.addWidget(self.SpinTOStartFrom, 0, 2, 1, 1)
        self.LblLblTOStartTo = QtWidgets.QLabel(self.TabTO)
        self.LblLblTOStartTo.setObjectName("LblLblTOStartTo")
        self.gridLayout_2.addWidget(self.LblLblTOStartTo, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.SpinToStartTo = QtWidgets.QSpinBox(self.TabTO)
        self.SpinToStartTo.setEnabled(False)
        self.SpinToStartTo.setMaximum(99999999)
        self.SpinToStartTo.setProperty("value", 1000)
        self.SpinToStartTo.setObjectName("SpinToStartTo")
        self.gridLayout_2.addWidget(self.SpinToStartTo, 0, 4, 1, 1)
        self.CBTOBrightness = QtWidgets.QCheckBox(self.TabTO)
        self.CBTOBrightness.setChecked(True)
        self.CBTOBrightness.setObjectName("CBTOBrightness")
        self.gridLayout_2.addWidget(self.CBTOBrightness, 1, 0, 1, 1)
        self.LblTOPeriodFrom = QtWidgets.QLabel(self.TabTO)
        self.LblTOPeriodFrom.setObjectName("LblTOPeriodFrom")
        self.gridLayout_2.addWidget(self.LblTOPeriodFrom, 2, 1, 1, 1)
        self.SpinToBrTo = QtWidgets.QSpinBox(self.TabTO)
        self.SpinToBrTo.setMaximum(255)
        self.SpinToBrTo.setProperty("value", 255)
        self.SpinToBrTo.setObjectName("SpinToBrTo")
        self.gridLayout_2.addWidget(self.SpinToBrTo, 1, 4, 1, 1)
        self.LblTOPeriodTo = QtWidgets.QLabel(self.TabTO)
        self.LblTOPeriodTo.setObjectName("LblTOPeriodTo")
        self.gridLayout_2.addWidget(self.LblTOPeriodTo, 2, 3, 1, 1)
        self.SpinToPeriodFrom = QtWidgets.QSpinBox(self.TabTO)
        self.SpinToPeriodFrom.setEnabled(False)
        self.SpinToPeriodFrom.setObjectName("SpinToPeriodFrom")
        self.gridLayout_2.addWidget(self.SpinToPeriodFrom, 2, 2, 1, 1)
        self.SpinTOPeriodTo = QtWidgets.QSpinBox(self.TabTO)
        self.SpinTOPeriodTo.setMaximum(999999)
        self.SpinTOPeriodTo.setProperty("value", 1000)
        self.SpinTOPeriodTo.setObjectName("SpinTOPeriodTo")
        self.gridLayout_2.addWidget(self.SpinTOPeriodTo, 2, 4, 1, 1)
        self.LblToBrTo = QtWidgets.QLabel(self.TabTO)
        self.LblToBrTo.setObjectName("LblToBrTo")
        self.gridLayout_2.addWidget(self.LblToBrTo, 1, 3, 1, 1)
        self.LblTOStartMs = QtWidgets.QLabel(self.TabTO)
        self.LblTOStartMs.setObjectName("LblTOStartMs")
        self.gridLayout_2.addWidget(self.LblTOStartMs, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.TabTO)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 5, 1, 1)
        self.tabWidget.addTab(self.TabTO, "")
        self.TabShine = QtWidgets.QWidget()
        self.TabShine.setObjectName("TabShine")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TabShine)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SpinShineBrTo = QtWidgets.QSpinBox(self.TabShine)
        self.SpinShineBrTo.setMaximum(255)
        self.SpinShineBrTo.setProperty("value", 255)
        self.SpinShineBrTo.setObjectName("SpinShineBrTo")
        self.gridLayout_3.addWidget(self.SpinShineBrTo, 0, 2, 1, 1)
        self.SpinShinePeriodFrom = QtWidgets.QSpinBox(self.TabShine)
        self.SpinShinePeriodFrom.setMaximum(99999999)
        self.SpinShinePeriodFrom.setObjectName("SpinShinePeriodFrom")
        self.gridLayout_3.addWidget(self.SpinShinePeriodFrom, 1, 1, 1, 1)
        self.SpinShinePeriodTo = QtWidgets.QSpinBox(self.TabShine)
        self.SpinShinePeriodTo.setMaximum(99999999)
        self.SpinShinePeriodTo.setObjectName("SpinShinePeriodTo")
        self.gridLayout_3.addWidget(self.SpinShinePeriodTo, 1, 2, 1, 1)
        self.LblShineBr = QtWidgets.QLabel(self.TabShine)
        self.LblShineBr.setObjectName("LblShineBr")
        self.gridLayout_3.addWidget(self.LblShineBr, 0, 0, 1, 1)
        self.SpinShineBrFrom = QtWidgets.QSpinBox(self.TabShine)
        self.SpinShineBrFrom.setMaximum(255)
        self.SpinShineBrFrom.setObjectName("SpinShineBrFrom")
        self.gridLayout_3.addWidget(self.SpinShineBrFrom, 0, 1, 1, 1)
        self.LblShinePeriod = QtWidgets.QLabel(self.TabShine)
        self.LblShinePeriod.setObjectName("LblShinePeriod")
        self.gridLayout_3.addWidget(self.LblShinePeriod, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        self.tabWidget.addTab(self.TabShine, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LblGroups = QtWidgets.QLabel(self.tab_2)
        self.LblGroups.setObjectName("LblGroups")
        self.gridLayout_4.addWidget(self.LblGroups, 0, 0, 1, 1)
        self.LblMove = QtWidgets.QLabel(self.tab_2)
        self.LblMove.setObjectName("LblMove")
        self.gridLayout_4.addWidget(self.LblMove, 5, 7, 1, 1)
        self.BtnAddGroup = QtWidgets.QPushButton(self.tab_2)
        self.BtnAddGroup.setObjectName("BtnAddGroup")
        self.gridLayout_4.addWidget(self.BtnAddGroup, 7, 0, 1, 1)
        self.LblLeds_2 = QtWidgets.QLabel(self.tab_2)
        self.LblLeds_2.setObjectName("LblLeds_2")
        self.gridLayout_4.addWidget(self.LblLeds_2, 0, 1, 1, 1)
        self.SpinShift = QtWidgets.QSpinBox(self.tab_2)
        self.SpinShift.setObjectName("SpinShift")
        self.gridLayout_4.addWidget(self.SpinShift, 6, 7, 1, 1)
        self.BtnAddLed = QtWidgets.QPushButton(self.tab_2)
        self.BtnAddLed.setObjectName("BtnAddLed")
        self.gridLayout_4.addWidget(self.BtnAddLed, 7, 1, 1, 1)
        self.BtnDeleteLed = QtWidgets.QPushButton(self.tab_2)
        self.BtnDeleteLed.setObjectName("BtnDeleteLed")
        self.gridLayout_4.addWidget(self.BtnDeleteLed, 7, 2, 1, 1)
        self.BtnLedUp_2 = QtWidgets.QPushButton(self.tab_2)
        self.BtnLedUp_2.setObjectName("BtnLedUp_2")
        self.gridLayout_4.addWidget(self.BtnLedUp_2, 7, 4, 1, 1)
        self.BtnLedUp = QtWidgets.QPushButton(self.tab_2)
        self.BtnLedUp.setObjectName("BtnLedUp")
        self.gridLayout_4.addWidget(self.BtnLedUp, 7, 3, 1, 1)
        self.LstGroups = QtWidgets.QListWidget(self.tab_2)
        self.LstGroups.setObjectName("LstGroups")
        self.gridLayout_4.addWidget(self.LstGroups, 2, 0, 5, 1)
        self.LblApply = QtWidgets.QLabel(self.tab_2)
        self.LblApply.setObjectName("LblApply")
        self.gridLayout_4.addWidget(self.LblApply, 3, 7, 1, 1)
        self.LblAvailable = QtWidgets.QLabel(self.tab_2)
        self.LblAvailable.setObjectName("LblAvailable")
        self.gridLayout_4.addWidget(self.LblAvailable, 0, 7, 1, 1)
        self.BtnAddEffect = QtWidgets.QPushButton(self.tab_2)
        self.BtnAddEffect.setObjectName("BtnAddEffect")
        self.gridLayout_4.addWidget(self.BtnAddEffect, 7, 5, 1, 1)
        self.BtnDeleteEffect = QtWidgets.QPushButton(self.tab_2)
        self.BtnDeleteEffect.setObjectName("BtnDeleteEffect")
        self.gridLayout_4.addWidget(self.BtnDeleteEffect, 7, 6, 1, 1)
        self.LblEffects = QtWidgets.QLabel(self.tab_2)
        self.LblEffects.setObjectName("LblEffects")
        self.gridLayout_4.addWidget(self.LblEffects, 0, 5, 1, 1)
        self.CBEffects = QtWidgets.QComboBox(self.tab_2)
        self.CBEffects.setObjectName("CBEffects")
        self.CBEffects.addItem("")
        self.CBEffects.addItem("")
        self.gridLayout_4.addWidget(self.CBEffects, 2, 7, 1, 1, QtCore.Qt.AlignTop)
        self.LstLeds = QtWidgets.QListWidget(self.tab_2)
        self.LstLeds.setObjectName("LstLeds")
        self.gridLayout_4.addWidget(self.LstLeds, 2, 1, 5, 4)
        self.LstEffects = QtWidgets.QListWidget(self.tab_2)
        self.LstEffects.setObjectName("LstEffects")
        self.gridLayout_4.addWidget(self.LstEffects, 2, 5, 5, 2)
        self.CBSequence = QtWidgets.QCheckBox(self.tab_2)
        self.CBSequence.setObjectName("CBSequence")
        self.gridLayout_4.addWidget(self.CBSequence, 4, 7, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 8, 0, 1, 9)
        self.CBBlue = QtWidgets.QCheckBox(self.centralwidget)
        self.CBBlue.setTristate(True)
        self.CBBlue.setObjectName("CBBlue")
        self.gridLayout.addWidget(self.CBBlue, 1, 2, 1, 1)
        self.CBGreen = QtWidgets.QCheckBox(self.centralwidget)
        self.CBGreen.setTristate(True)
        self.CBGreen.setObjectName("CBGreen")
        self.gridLayout.addWidget(self.CBGreen, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CBB1.setText(_translate("MainWindow", "B1"))
        self.CBG29.setText(_translate("MainWindow", "G29"))
        self.CBG28.setText(_translate("MainWindow", "G28"))
        self.CBG1.setText(_translate("MainWindow", "G1"))
        self.CBG7.setText(_translate("MainWindow", "G7"))
        self.CBG31.setText(_translate("MainWindow", "G31"))
        self.CBG21.setText(_translate("MainWindow", "G21"))
        self.CBG27.setText(_translate("MainWindow", "G27"))
        self.CBG10.setText(_translate("MainWindow", "G10"))
        self.CBB2.setText(_translate("MainWindow", "B2"))
        self.CBG12.setText(_translate("MainWindow", "G12"))
        self.CBB3.setText(_translate("MainWindow", "B3"))
        self.CBG2.setText(_translate("MainWindow", "G2"))
        self.CBG5.setText(_translate("MainWindow", "G5"))
        self.CBB9.setText(_translate("MainWindow", "B9"))
        self.CBG6.setText(_translate("MainWindow", "G6"))
        self.CBG18.setText(_translate("MainWindow", "G18"))
        self.CBG33.setText(_translate("MainWindow", "G33"))
        self.CBG9.setText(_translate("MainWindow", "G9"))
        self.CBB6.setText(_translate("MainWindow", "B6"))
        self.CBG8.setText(_translate("MainWindow", "G8"))
        self.CBG22.setText(_translate("MainWindow", "G22"))
        self.CBG30.setText(_translate("MainWindow", "G30"))
        self.CBG24.setText(_translate("MainWindow", "G24"))
        self.BtnCreate.setText(_translate("MainWindow", "Создать эффект для выбранных диодов"))
        self.LblLeds.setText(_translate("MainWindow", "Выберите светодиоды для эффекта:"))
        self.CBG34.setText(_translate("MainWindow", "G34"))
        self.CBG11.setText(_translate("MainWindow", "G11"))
        self.CBG3.setText(_translate("MainWindow", "G3"))
        self.CBG19.setText(_translate("MainWindow", "G19"))
        self.CBG26.setText(_translate("MainWindow", "G26"))
        self.CBG36.setText(_translate("MainWindow", "G36"))
        self.CBG32.setText(_translate("MainWindow", "G32"))
        self.CBG14.setText(_translate("MainWindow", "G14"))
        self.CBG23.setText(_translate("MainWindow", "G23"))
        self.CBG4.setText(_translate("MainWindow", "G4"))
        self.CBG25.setText(_translate("MainWindow", "G25"))
        self.CBG20.setText(_translate("MainWindow", "G20"))
        self.CBG17.setText(_translate("MainWindow", "G17"))
        self.CBG16.setText(_translate("MainWindow", "G16"))
        self.CBB8.setText(_translate("MainWindow", "B8"))
        self.CBB5.setText(_translate("MainWindow", "B5"))
        self.CBG35.setText(_translate("MainWindow", "G35"))
        self.CBG15.setText(_translate("MainWindow", "G15"))
        self.CBB4.setText(_translate("MainWindow", "B4"))
        self.CBAll.setText(_translate("MainWindow", "Выбрать/сбросить все"))
        self.CBB7.setText(_translate("MainWindow", "B7"))
        self.CBG13.setText(_translate("MainWindow", "G13"))
        self.LblTOStartFrom.setText(_translate("MainWindow", "От"))
        self.CBTOStart.setText(_translate("MainWindow", "Одновременный старт"))
        self.CBTOPeriod.setText(_translate("MainWindow", "Одинаковый период"))
        self.LblTOBrFrom.setText(_translate("MainWindow", "От"))
        self.LblLblTOStartTo.setText(_translate("MainWindow", "До"))
        self.CBTOBrightness.setText(_translate("MainWindow", "Одинаковая яркость"))
        self.LblTOPeriodFrom.setText(_translate("MainWindow", "От"))
        self.LblTOPeriodTo.setText(_translate("MainWindow", "До"))
        self.LblToBrTo.setText(_translate("MainWindow", "До"))
        self.LblTOStartMs.setText(_translate("MainWindow", "ms"))
        self.label.setText(_translate("MainWindow", "ms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabTO), _translate("MainWindow", "Turn on"))
        self.LblShineBr.setText(_translate("MainWindow", "Яркость:"))
        self.LblShinePeriod.setText(_translate("MainWindow", "Период"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabShine), _translate("MainWindow", "Сияние"))
        self.LblGroups.setText(_translate("MainWindow", "Список групп:"))
        self.LblMove.setText(_translate("MainWindow", "Со сдвигом, ms:"))
        self.BtnAddGroup.setText(_translate("MainWindow", "Добавить группу"))
        self.LblLeds_2.setText(_translate("MainWindow", "Диоды в группе:"))
        self.BtnAddLed.setText(_translate("MainWindow", "Добавить"))
        self.BtnDeleteLed.setText(_translate("MainWindow", "Удалить"))
        self.BtnLedUp_2.setText(_translate("MainWindow", "Выше"))
        self.BtnLedUp.setText(_translate("MainWindow", "Ниже"))
        self.LblApply.setText(_translate("MainWindow", "Эффекты применить"))
        self.LblAvailable.setText(_translate("MainWindow", "Доступные эффекты:"))
        self.BtnAddEffect.setText(_translate("MainWindow", "Добавить"))
        self.BtnDeleteEffect.setText(_translate("MainWindow", "Удалить"))
        self.LblEffects.setText(_translate("MainWindow", "Эффекты группы:"))
        self.CBEffects.setItemText(0, _translate("MainWindow", "Зажечь"))
        self.CBEffects.setItemText(1, _translate("MainWindow", "Сияние"))
        self.CBSequence.setText(_translate("MainWindow", "Друг за другом"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Кастомный эффект"))
        self.CBBlue.setText(_translate("MainWindow", "Все синие"))
        self.CBGreen.setText(_translate("MainWindow", "Все зеленые"))

